/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_READER_RUST_FFI__
#define __RUST_READER_RUST_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  对已经取得的响应进行离线规则诊断；该函数绝不主动发起 HTTP 请求。
 */
char *
debug_parse (
    char const * source_json,
    char const * html_body,
    char const * base_url,
    char const * mode);

/** \brief
 *  通用规则/求值/清洗/微指令入口。该函数保持 ABI v1 已有语义，但不承担书源抓取。
 */
char *
reader_eval (
    char const * input,
    char const * rule);

/** \brief
 *  ABI v2 书源业务入口：SO 自行完成 URL 规则、HTTP、Cookie、分页和解析。
 */
char *
reader_execute (
    char const * source_json,
    char const * request_json);

/** \brief
 *  释放所有 `reader_*` 返回给 C/Lua 的字符串。每个非空指针必须且只能释放一次。
 */
void
reader_free_string (
    char * value);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_READER_RUST_FFI__ */
