/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_READER_RUST_FFI__
#define __RUST_READER_RUST_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  通用规则/求值/清洗/微指令入口。该函数保持 ABI v1 已有语义，但不承担书源抓取。
 */
char *
reader_eval (
    char const * input,
    char const * rule);

/** \brief
 *  ABI v2 书源业务入口：SO 自行完成 URL 规则、HTTP、Cookie、分页和解析。
 */
char *
reader_execute (
    char const * source_json,
    char const * request_json);

/** \brief
 *  释放所有 `reader_*` 返回给 C/Lua 的字符串。每个非空指针必须且只能释放一次。
 */
void
reader_free_string (
    char * value);


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
typedef struct ReaderHostServices {
    /** <No documentation available> */
    uint32_t abi_version;

    /** <No documentation available> */
    int32_t (*call)(void *, char const *, char const *, uint8_t *, size_t);

    /** <No documentation available> */
    void * user_data;

    /** \brief
     *  Zero selects 64 KiB. Maximum is 8 MiB. Calls are never replayed to resize.
     */
    size_t max_response_bytes;
} ReaderHostServices_t;

/** \brief
 *  Register services in this thread/process. NULL unregisters; host owns pointers.
 *  Returns 0 on success, -1 for invalid configuration, -2 during a host callback.
 *  # Safety
 *  The host must keep callback/user_data alive until unregistering and obey the
 *  callback's buffer, same-thread and non-unwinding contract.
 */
int32_t
reader_set_host_services (
    ReaderHostServices_t const * services);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_READER_RUST_FFI__ */
