name: Build FFI Library

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-linux-androideabi
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabi
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
        include:
          - target: armv7-linux-androideabi
            asset_name: libreader_parser-android-armv7.so
          - target: armv7-unknown-linux-gnueabihf
            asset_name: libreader_parser-linux-armv7hf.so
          - target: armv7-unknown-linux-gnueabi
            asset_name: libreader_parser-linux-armv7sf.so
          - target: aarch64-unknown-linux-gnu
            asset_name: libreader_parser-linux-aarch64.so
          - target: x86_64-unknown-linux-gnu
            asset_name: libreader_parser-linux-x86_64.so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: |
          curl -L https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz | tar xz -C ~/.cargo/bin

      - name: Build Library
        run: cross build --target ${{ matrix.target }} --release

      - name: Rename Artifact
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/libreader_parser.so target/${{ matrix.target }}/release/${{ matrix.asset_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reader-parser-ffi-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.asset_name }}
          if-no-files-found: error
